version: '3.8'

services:
  frontend:
    # dockerfile로 이미지 생성하기
    build:
      context: ../vue
      dockerfile: ../vue/Dockerfile
      # dockerfile에게 환경변수를 넘겨준다.
      args:
        - VITE_BACKEND_URL=https://www.facet7.kro.kr/api
    ports:
      - "80:80"  # 나중에 인증서 하면 443번으로 하기
      - "443:443"
    depends_on:
      - backend
